### PR TITLE
- enable caching of game objects for the ItemsControl.cs

### PR DESCRIPTION
**Pull request by JustinSavinoMicrosoft**
- instantiates a pool of game objects on Awake() based on the item template and then enables/disables those game objects when items need them

### CODE REVIEW

**Review by jbruening — COMMENTED** [review]
I think the pooling behavior should be separated out into an interface with Create and Destroy methods, with a default implementation+instance with standard unity non-pooling behavior.  Then move the caching behavior you've added into its own implementation of the interface.

**Comment by hendryems** [comment]
Hi @jbruening , thanks for taking a look at this change and providing feedback!

On a slightly relevant topic - the previous collaborators from our group, @ryantrem & @AdamMitchell-ms, have both moved on to other projects and no longer actively monitoring changes to this repo. Would you be open to extending the invitation of adding new collaborators from our group (e.g. @jonathoncobb) to help code review and approve changes moving forward?

We love to be able to continue contributing directly to this repo instead of looking to fork it. Let me know what you think!

**Comment by jbruening** [comment]
I've added jonathoncobb, let me know who else is in your group.

**Comment by hendryems** [comment]
> I've added jonathoncobb, let me know who else is in your group.

Can you also help add myself. That should be good for now. Thanks again @jbruening!

**Comment by JustinSavinoMicrosoft** [comment]
Hi @jbruening, I have separated out the creating and destroying behaviors into implemented interfaces. By default it uses the default implementation of the interface.

**Pull request merged**
